version: "3.8"
services:
  plex-meta-manager:
    image: lscr.io/linuxserver/plex-meta-manager:latest
    container_name: plex-meta-manager
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PMM_CONFIG=/config/config.yml #optional
      - PMM_TIME=03:00 #optional
      - PMM_RUN=False #optional
      - PMM_TEST=False #optional
      - PMM_NO_MISSING=False #optional
    volumes:
      - /home/user/docker/plex-meta-manager/config:/config
    restart: unless-stopped
    networks:
      proxy:
    security_opt:
      - no-new-privileges:true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.plex-meta-manager.entrypoints=http"
      - "traefik.http.routers.plex-meta-manager.rule=Host(`plex-meta-manager.user.ru`)"
      - "traefik.http.middlewares.plex-meta-manager-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.plex-meta-manager.middlewares=plex-meta-manager-https-redirect"
      - "traefik.http.routers.plex-meta-manager-secure.entrypoints=https"
      - "traefik.http.routers.plex-meta-manager-secure.rule=Host(`plex-meta-manager.user.ru`)"
      - "traefik.http.routers.plex-meta-manager-secure.tls=true"
      - "traefik.http.routers.plex-meta-manager-secure.service=plex-meta-manager"
      - "traefik.http.services.plex-meta-manager.loadbalancer.server.port=9000"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true
