http:
  routers:
    cockpit:
      entryPoints:
        - "https"
      rule: "Host(`cockpit.domain.ru`)"        # Change DOMAIN_NAME to yours
      middlewares:
        - default-headers
        - https-redirect
      tls: {}
      service: cockpit
    #end region
  services:
    #nextcloud:
    #  loadBalancer:
    #    servers:
    #      - url: "http://192.168.0.0:8080"
    #    passHostHeader: true
    cockpit:
      loadBalancer:
        servers:
          - url: "https://192.168.0.0:9090"
        passHostHeader: true
  #end region
  middlewares:
    authentik: #note the name of middleware and authentik container name
      forwardAuth:
        address: "http://authentik_server:9000/outpost.goauthentik.io/auth/traefik"
        trustForwardHeader: true
        authResponseHeaders:
          - X-authentik-username
          - X-authentik-groups
          - X-authentik-email
          - X-authentik-name
          - X-authentik-uid
          - X-authentik-jwt
          - X-authentik-meta-jwks
          - X-authentik-meta-outpost
          - X-authentik-meta-provider
          - X-authentik-meta-app
          - X-authentik-meta-version

    nextcloud-secure-headers:
      headers:
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        referrerPolicy: "same-origin"
        customResponseHeaders:
          X-Robots-Tag: "noindex, nofollow"

    https-redirect:
      redirectScheme:
        scheme: https
        permanent: true
    
    default-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https

    nextcloud-chain:
      chain:
        middlewares:
          # - ... (e.g. rate limiting middleware)
          - https-redirect
          - nextcloud-secure-headers
          - default-headers
                      
    default-whitelist:
      IPAllowList:
        sourceRange:
        - "192.168.0.0/16"

    secured:
      chain:
        middlewares:
        - default-whitelist
        - default-headers