version: "3.5"

services:
  diun:
    image: crazymax/diun:latest
    container_name: diun
    command: serve #comment if using podman
    # security_opt is neccessary if you use podman in rootless mode to apply the correct SELinux rules
    #security_opt:
    #  - "label=type:container_runtime_t"
    volumes:
      - "/home/stilicho/docker/diun/data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock" #/run/podman/podman.sock instead var/run/docker.sock if using podman
    environment:
      - "TZ=Europe/Moscow"
      - "LOG_LEVEL=info"
      - "DIUN_WATCH_WORKERS=20"
      - "DIUN_WATCH_SCHEDULE=0 */6 * * *"
      - "DIUN_WATCH_JITTER=30s"
      - "DIUN_WATCH_RUNONSTARTUP=true"
      - "DIUN_PROVIDERS_DOCKER=true"
      - "DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT=true"

      #- "DIUN_NOTIF_TELEGRAM_TOKEN=1111111111:asdbksdfkljsdlkfjsdf"
      #- "DIUN_NOTIF_TELEGRAM_chatIDs=123456789"
      
      - "DIUN_NOTIF_GOTIFY_ENDPOINT=https://gotify.domain.ru"
      - "DIUN_NOTIF_GOTIFY_TOKEN=ABCDEFGHHGJHG" # get your token from Gotify UI
      - "DIUN_NOTIF_GOTIFY_PRIORITY=1"
      - "DIUN_NOTIF_GOTIFY_TIMEOUT=10s"
    labels:
      - "diun.enable=true"
    restart: always