version: "3.8"

services:
recyclarr:
    image: ghcr.io/recyclarr/recyclarr
    container_name: recyclarr
    user: 1000:1000
    volumes:
      - /home/user/docker/torrents/recyclarr:/config
    environment:
      - TZ=Europe/Moscow
    networks:
      - proxy

networks:
  proxy:
    external: true