################################################################
# Middlewares 
# https://doc.traefik.io/traefik/middlewares/http/ipallowlist/
# Dynamic configuration
################################################################
http:
  middlewares:
    default-whitelist:
      IPAllowList:
        sourceRange:
        - "10.0.0.0/8"
        - "192.168.0.0/16"
        - "172.16.0.0/12"