version: "3.8"

services:
  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 7878:7878
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/stilicho/torrents/radarr:/config
      - /mnt/media:/data
    networks:
      - arr	

  sonarr:
    container_name: sonarr
    image: ghcr.io/hotio/sonarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 8989:8989
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/stilicho/torrents/sonarr:/config
      - /mnt/media:/data
    networks:
      -arr

  prowlarr:
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr:latest
    restart: unless-stopped
    ports:
      - "9696:9696"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Moscow
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/stilicho/torrents/prowlarr:/config
    networks:
      -arr

  bazarr:
    container_name: bazarr
    image: ghcr.io/hotio/bazarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 6767:6767
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/stilicho/torrents/bazarr:/config
      - /mnt/media:/data/media
    networks:
      - arr

  qbittorrent:
    container_name: qbittorrent
    image: ghcr.io/hotio/qbittorrent:latest
    ports:
      - 10095:8080
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Moscow
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/stilicho/torrents/qbittorrent:/config
      - /mnt/media/torrents:/data
    restart: unless-stopped
    networks:
      -arr
          
  lidarr:
    container_name: lidarr
    image: ghcr.io/hotio/lidarr:latest
    ports:
        - 8686:8686
    environment:
        - PUID=1000
        - PGID=1000
        - UNMASK=022
        - TZ=Europe/Moscow
    volumes:
        - /etc/localtime:/etc/localtime:ro
        - /home/stilicho/torrents/lidarr:/config
        - /mnt/media:/music
    restart: unless-stopped
    networks:
        - arr
           			
  recyclarr:
    container_name: recyclarr
    image: ghcr.io/recyclarr/recyclarr:latest
    user: 1000:1000
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002	
      - TZ=Europe/Moscow
      - CRON_SCHEDULE: "* * * * *"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/stilicho/torrents/recyclarr:/config
    networks:
      - arr
	  
  overseerr:
    container_name: overseerr
    image: ghcr.io/hotio/overseerr:latest
    ports:
      - 5055:5055
    environment:
      - LOG_LEVEL=info
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Moscow
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/stilicho/torrents/overseerr:/config
    restart: unless-stopped
    networks:
      - arr
	   
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/Moscow
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped
    networks:
      - arr

networks:
  arr:
    external: true
